version: '3.8'
services:
  db:
    container_name: travel_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: travel_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data: